### ISSUE TITLE
Enable Haraka's HTTP server (see listen in http.ini)

### ISSUE THREAD

**Issue by pakshan** [haraka/haraka-plugin-watch#45]
I don't know how to enable that http server.
These are what i did:
npm install -g express.js
add listen=[::0] in config/http.ini file
add watch in config/plugins file
start haraka and i got this errors:

$ sudo haraka -c .
loaded TLD files: 1=1508 2=8565 3=2448
loaded 8995 Public Suffixes
loglevel: INFO
log format: DEFAULT
loglevel: LOGINFO
Starting up Haraka version 2.8.26
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: dnsbl
[INFO] [-] [core] Loading plugin: helo.checks
[INFO] [-] [core] Loading plugin: tls
[INFO] [-] [core] loading tls.ini
[INFO] [-] [core] Loading plugin: auth/flat_file
[INFO] [-] [core] Loading plugin: mail_from.is_resolvable
[INFO] [-] [core] Loading plugin: rcpt_to.in_host_list
[INFO] [-] [core] Loading plugin: headers
[INFO] [-] [core] Loading plugin: dkim_sign
[INFO] [-] [core] Loading plugin: watch
[NOTICE] [-] [core] Listening on [::0]:587
[INFO] [-] [core] [outbound] Loading outbound queue from /home/ubuntu/hoshi/haraka/queue
[INFO] [-] [core] express loaded at Server.http.express
[INFO] [-] [core] express app is at Server.http.app
[NOTICE] [-] [core] Listening on [::0]:8080
[INFO] [-] [watch] watch init_http done
[INFO] [-] [core] init_http_respond
[INFO] [-] [core] Server.http.wss loaded
[INFO] [-] [watch] watch init_wss
[INFO] [-] [watch] watch init_wss done
[INFO] [-] [core] init_wss_respond
[INFO] [-] [core] using html docroot: /home/ubuntu/hoshi/haraka/html
[INFO] [-] [core] [outbound] Loading the queue...
[INFO] [-] [core] [outbound] [pid: undefined] 0 files in my delivery queue
[INFO] [-] [core] [outbound] [pid: undefined] 0 files in my load queue
[INFO] [-] [core] [outbound] [pid: undefined] 0 files in my temp fail queue
[ERROR] [-] [server] watch plugin ran callback multiple times - ignoring subsequent calls
[ERROR] [-] [server] Error
    at callback (/usr/lib/node_modules/Haraka/plugins.js:484:34)                                       
    at /usr/lib/node_modules/Haraka/node_modules/haraka-plugin-watch/index.js:273:5                    
    at RedisClient.<anonymous> (/usr/lib/node_modules/Haraka/node_modules/haraka-plugin-redis/index.js:179:13)                                                                                                
    at RedisClient.emit (events.js:315:20)                                                             
    at RedisClient.on_error (/usr/lib/node_modules/Haraka/node_modules/redis/index.js:341:14)          
    at Socket.<anonymous> (/usr/lib/node_modules/Haraka/node_modules/redis/index.js:222:14)            
    at Socket.emit (events.js:315:20)                                                                  
    at emitErrorNT (internal/streams/destroy.js:106:8)                                                 
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)                                             
    at processTicksAndRejections (internal/process/task_queues.js:80:21)                               
[ERROR] [-] [server] watch plugin ran callback multiple times - ignoring subsequent calls
[ERROR] [-] [server] Error
    at callback (/usr/lib/node_modules/Haraka/plugins.js:484:34)        
....

**Comment by msimerson** [comment]
It appears you don't have Redis installed. That is required.
