### ISSUE TITLE
Watch not working. Getting 404 on wss_conf from client.js

### ISSUE THREAD

**Issue by true2thepen** [haraka/haraka-plugin-watch#59]
Hello,

I'm getting the following in developer tools when running watch.

client.js:172

GET http://mydomain.com:82/watch/wss_conf 404 (Not Found)

jquery-3.7.1.min.js:2 jQuery.Deferred exception: Unexpected token '<', "<!DOCTYPE "... is not valid JSON SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at httpGetJSON (http://mydomain.com:82/watch/client.js:173:15)
    at ws_connect (http://mydomain.com:82/watch/client.js:183:18)
    at HTMLDocument.<anonymous> (http://mydomain.com:82/watch/:31:3)
    at e (http://code.jquery.com/jquery-3.7.1.min.js:2:27028)
    at t (http://code.jquery.com/jquery-3.7.1.min.js:2:27330)

jquery-3.7.1.min.js:2 Uncaught SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at httpGetJSON (client.js:173:15)
    at ws_connect (client.js:183:18)  
    at HTMLDocument.<anonymous> (watch/:31:3)
    at e (jquery-3.7.1.min.js:2:27028)

What is wss_conf and what is supposed to be in this file?

**Comment by msimerson** [comment]
I can't replicate. Please provide the versions of Haraka, node.js, and this plugin.

**Comment by msimerson** [comment]
> What is wss_conf and what is supposed to be in this file?

It's a dynamic URL ([here in code](https://github.com/haraka/haraka-plugin-watch/blob/master/index.js#L37)) that tells the HTTP client where to find the WSS endpoint.

**Comment by true2thepen** [comment]
Haraka version 3.0.2
Watch 2.0.4
Node 20.10.0

I removed the plugin, re-installed and I now have it working. No clue as to what the problem was. Was getting different errors depending upon the browser used. I'm closing this since it is now working. Thanks for your time.
